name: ci-sum
on: [push]
jobs:
    check:
          runs-on: ubuntu-latest
          steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-veersion: 3.13
          - run: pip intall -r requirements.txt
          - run: pytest