name: ci-sum
on: [push]
jobs:
    check:
          runs-on: ubuntu-latest
          steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-veersion: 3.13
          - run: pip install -r requirements.txt
          - run: pytest
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build
            uses: docker/build-push-action@v3
            with:
              push: false
              tags: ci-sum-2025